# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pr:
  autoCancel: false
  branches:
    include:
    - '*'

pool:
  vmImage: 'windows-latest'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    includePreviewVersions: true
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '**/*.Test.csproj'
    arguments: '--configuration Release'
    
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: 'pack'
    packagesToPack: 'Jakamo.Api/src/Jakamo.Api.csproj'
    configuration: 'Release'
    versioningScheme: 'off'

- powershell: |
    choco install docfx -y --version 2.58.5
    docfx Jakamo.Api/doc/docfx.json
    if ($lastexitcode -ne 0){
      throw ("Error generating document")
    }
  displayName: "Documentation"
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/Jakamo.Api/doc/_site'
    ArtifactName: 'docs'
    publishLocation: 'Container'
- task: DotNetCoreCLI@2
  displayName: Push NuGet package
  inputs:
    command: custom
    custom: nuget
    arguments: >
      push $(Agent.BuildDirectory)/**/*.nupkg
      -s https://api.nuget.org/v3/index.json
      -k $(NuGetApiKey)